<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libphonenumber-csharp" Version="9.0.35" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YaeaY.Account.Application\YaeaY.Account.Application.csproj" />
    <ProjectReference Include="..\YaeaY.Account.Domain\YaeaY.Account.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Messaging\" />
  </ItemGroup>

</Project>
