name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: self-hosted

    steps:
      - name: Update source
        run: |
          cd /opt/yaeay/apps/yaeay-account/source
          git fetch origin
          git checkout develop
          git reset --hard origin/develop

      - name: Deploy dev
        run: |
          cd /opt/yaeay/apps/yaeay-account/environments/dev/compose
          docker compose up -d --build

      - name: Show containers
        run: |
          cd /opt/yaeay/apps/yaeay-account/environments/dev/compose
          docker compose ps
